#!/bin/bash
source /usr/local/sbin/base-script

clear
echo -e "$TITLE" | lolcat -a
echo '                                                              
    ██████╗ ███████╗██╗  ██╗████████╗███████╗██████╗        
    ██╔══██╗██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝██╔══██╗       
    ██║  ██║█████╗   ╚███╔╝    ██║   █████╗  ██████╔╝       
    ██║  ██║██╔══╝   ██╔██╗    ██║   ██╔══╝  ██╔══██╗       
    ██████╔╝███████╗██╔╝ ██╗   ██║   ███████╗██║  ██║       
    ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝       
'
echo -e ""
echo -e "$GRN1 MultiLogin"
echo -e "$GRN2 Restart Services"
echo -e "$GRN3 Reboot"
echo -e "$GRN4 Exit"
echo -e ""
read -p "$(echo -e " Select from options\e[32m [\e[0m1-5\e[32m]\e[0m: ")" Options
echo -e ""
sleep 2
clear
case $Options in
		1)
		clear
		set_multilogin_autokill
		exit
		;;
		2)
		clear
		restart_services
		exit
		;;
		3)
		clear
		reboot_sys
		exit
		;;
		4)
		clear
		exit
		;;
	esac