#!/bin/bash

clear
echo -e ""
echo -e " =•= 24clanSSH VPN  Script By Farukbrowser =•= " | lolcat -a
echo -e ""
echo -e "   [1] Reboot Now"
echo -e "   [2] Exit"
echo -e ""
read -p "   Select from options [1-3]: " Reboot
echo -e ""
sleep 3
clear
case $Reboot in
		1)
		clear
		reboot
		exit
		;;
		2)
		clear
		exit
		;;
	esac